### ISSUE TITLE
 Look into custom fonts

### ISSUE THREAD

**Issue by mciethan** [bpda-research-division/neighborhood-change#28]
R Shiny doesn't support many fonts by default. We should look into installing custom fonts into the app somehow.

Sam suggested Source Sans Pro
Mandy suggested Lato and Roboto

**Comment by anonuser36** [comment]
Can create a css file to control all body fonts and add Open Sans ttf files to the www folder to allow custom fonts to be displayed regardless of browser defaults.

**Comment by mciethan** [comment]
Fixed by #55
