### ISSUE TITLE
Implement loading screens when changing topic

### ISSUE THREAD

**Issue by mciethan** [bpda-research-division/neighborhood-change#43]
To help avoid confusion about when the controls can be used after a new topic is selected.

https://cran.r-project.org/web/packages/shinybusy/vignettes/shinybusy.html
https://rdrr.io/github/dreamRs/shinybusy/src/examples/use_busy_spinner.R
https://stackoverflow.com/questions/49488228/how-to-show-spinning-wheel-or-busy-icon-while-waiting-in-shiny

**Comment by anonuser36** [comment]
Found a solution using the [leaflet.extras2 package](https://trafficonese.github.io/leaflet.extras2/) and the addSpinner()/startSpinner()/stopSpinner() functions! The package incorporates some plugins (like[ spin.js](https://spin.js.org/)) available to standard Leaflet and makes them possible in Shiny. Simply wrap the calls to create a leaflet map in server.R with these functions, starting when all shapes are removed and stopping right before the correct shapes are added back. Yay!

**Comment by anonuser36** [comment]
The loading spinners for the graphs can be added most simply using the [shinycssloaders ](https://github.com/daattali/shinycssloaders) package. Add these in ui.R by wrapping the plotlyOutputs with withSpinner().

**Comment by mciethan** [comment]
Fixed by #54
